name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      
      - name: Install Flet
        run: pip install flet telethon
        
      - name: Build APK (Force Mode)
        run: |
          # Принудительная инициализация и сборка
          flet build apk --yes
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faza-messenger-final
          path: build/apk/**/*.apk
          
