name: Build Android APK
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Install Dependencies
        run: |
          pip install flet telethon
          
      - name: Build APK (Faza Edition)
        run: |
          # Собираем проект из текущей папки
          flet build apk --project . --yes
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: faza-messenger-final
          path: build/apk/**/*.apk
          
